// Generated by scripts/component-docs.ts — do not edit.
import { descriptor as checklist_v1 } from './checklist/v1'
import { descriptor as datatable_v1 } from './datatable/v1'
import { descriptor as embed_v1 } from './embed/v1'
import { descriptor as figure_v1 } from './figure/v1'

export const GENERATED_DESCRIPTORS = [checklist_v1, datatable_v1, embed_v1, figure_v1] as const
