'use client'
// Generated by scripts/component-docs.ts — do not edit.
import type { ComponentRenderer } from './types'
import { Render as checklist_v1 } from './checklist/v1/render'
import { Render as datatable_v1 } from './datatable/v1/render'
import { Render as embed_v1 } from './embed/v1/render'
import { Render as figure_v1 } from './figure/v1/render'

// biome-ignore lint/suspicious/noExplicitAny: data is validated by the registry before dispatch
export const GENERATED_RENDERERS: Record<string, ComponentRenderer<any>> = {
  'checklist@1': checklist_v1,
  'datatable@1': datatable_v1,
  'embed@1': embed_v1,
  'figure@1': figure_v1,
}
