/**
 * Single source of truth → generated artifacts.
 *
 * Every component version is one directory `apps/web/lib/components/<type>/v<N>/`
 * exporting `descriptor` (`index.ts`) and `Render` (`render.tsx`). This script
 * scans those directories, imports the descriptors, and writes the generated
 * outputs:
 *
 *   - apps/web/lib/components/registry.generated.ts      descriptor barrel
 *   - apps/web/lib/components/renderers.generated.tsx     renderer barrel
 *   - packages/core/src/wiki/component-names.generated.ts core's name list
 *   - packages/skills/memon-components/SKILL.md           the marked table
 *   - .claude/skills/memon-components/SKILL.md            byte copy, if present
 *
 * It must run inside the `@memon/web` workspace so the descriptors' `zod`
 * import resolves:
 *
 *   pnpm --filter @memon/web exec tsx ../../scripts/component-docs.ts --write
 *
 * `scripts/component-docs.mjs` is a wrapper that spawns exactly that, so
 * `node scripts/component-docs.mjs --check` works from the repository root.
 */

import { existsSync } from 'node:fs'
import { readFile, readdir, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import type { ComponentDescriptor } from '../apps/web/lib/components/types'

const repoRoot = new URL('../', import.meta.url)
const componentsDir = new URL('apps/web/lib/components/', repoRoot)

const OUTPUTS = {
  registry: new URL('registry.generated.ts', componentsDir),
  renderers: new URL('renderers.generated.tsx', componentsDir),
  names: new URL('packages/core/src/wiki/component-names.generated.ts', repoRoot),
  skill: new URL('packages/skills/memon-components/SKILL.md', repoRoot),
  /**
   * Byte copy of the skill for this repository's own agents. It only exists in
   * the harness checkout, so it is written/checked only when already present —
   * without it the copy silently rots on every descriptor edit.
   */
  claudeSkill: new URL('.claude/skills/memon-components/SKILL.md', repoRoot),
} as const

const BANNER = '// Generated by scripts/component-docs.ts — do not edit.'
const SKILL_START = '<!-- component-table:start -->'
const SKILL_END = '<!-- component-table:end -->'

// ---------------------------------------------------------------- discovery

interface Loaded {
  descriptor: ComponentDescriptor
  /** Import specifier relative to `apps/web/lib/components/`. */
  dir: string
}

const VERSION_DIR = /^v(\d+)$/

async function loadDescriptors(): Promise<Loaded[]> {
  const loaded: Loaded[] = []
  for (const typeEntry of await readdir(componentsDir, { withFileTypes: true })) {
    if (!typeEntry.isDirectory()) continue
    const typeDir = new URL(`${typeEntry.name}/`, componentsDir)
    for (const versionEntry of await readdir(typeDir, { withFileTypes: true })) {
      if (!versionEntry.isDirectory() || !VERSION_DIR.test(versionEntry.name)) continue
      const dir = `${typeEntry.name}/${versionEntry.name}`
      // Plugin-style load: the descriptor directories are discovered at run
      // time, so the specifier cannot be a literal.
      const module: unknown = await import(new URL(`${dir}/index.ts`, componentsDir).href)
      if (!module || typeof module !== 'object' || !('descriptor' in module)) {
        throw new Error(`${dir}/index.ts does not export \`descriptor\``)
      }
      const descriptor = module.descriptor as ComponentDescriptor
      if (descriptor.type !== typeEntry.name || `v${descriptor.version}` !== versionEntry.name) {
        throw new Error(
          `${dir}/index.ts declares ${descriptor.type}@${descriptor.version}, which does not match its directory`,
        )
      }
      loaded.push({ descriptor, dir })
    }
  }
  // Plain codepoint order, not `localeCompare`: these bytes are compared by
  // `--check` on every machine that builds the repo.
  loaded.sort((a, b) => {
    if (a.descriptor.type !== b.descriptor.type) return a.descriptor.type < b.descriptor.type ? -1 : 1
    return a.descriptor.version - b.descriptor.version
  })
  if (loaded.length === 0) throw new Error(`no component descriptors under ${componentsDir.pathname}`)
  return loaded
}

/** `datatable@1` → `datatable_v1`, usable as a TypeScript identifier. */
function alias(descriptor: ComponentDescriptor): string {
  return `${descriptor.type.replace(/-/g, '_')}_v${descriptor.version}`
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/

// ------------------------------------------------------------ TS artifacts

function renderRegistry(loaded: Loaded[]): string {
  const imports = loaded.map((e) => `import { descriptor as ${alias(e.descriptor)} } from './${e.dir}'`)
  const list = loaded.map((e) => alias(e.descriptor)).join(', ')
  return `${BANNER}\n${imports.join('\n')}\n\nexport const GENERATED_DESCRIPTORS = [${list}] as const\n`
}

function renderRenderers(loaded: Loaded[]): string {
  const imports = loaded.map(
    (e) => `import { Render as ${alias(e.descriptor)} } from './${e.dir}/render'`,
  )
  const entries = loaded.map(
    (e) => `  '${e.descriptor.type}@${e.descriptor.version}': ${alias(e.descriptor)},`,
  )
  return [
    "'use client'",
    BANNER,
    "import type { ComponentRenderer } from './types'",
    ...imports,
    '',
    '// biome-ignore lint/suspicious/noExplicitAny: data is validated by the registry before dispatch',
    'export const GENERATED_RENDERERS: Record<string, ComponentRenderer<any>> = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

function renderNames(loaded: Loaded[]): string {
  const latest = latestByType(loaded)
  const types = [...latest.keys()]
  const list = types.map((type) => `'${type}'`).join(', ')
  const entries = types.map(
    (type) => `  ${IDENTIFIER.test(type) ? type : `'${type}'`}: ${latest.get(type)!.version},`,
  )
  return [
    BANNER,
    `export const COMPONENT_TYPES = [${list}] as const`,
    'export const COMPONENT_LATEST_VERSION: Record<string, number> = {',
    ...entries,
    '}',
    '',
  ].join('\n')
}

/** Type → its highest-version descriptor, in type order. */
function latestByType(loaded: Loaded[]): Map<string, ComponentDescriptor> {
  const latest = new Map<string, ComponentDescriptor>()
  for (const { descriptor } of loaded) {
    const current = latest.get(descriptor.type)
    if (!current || descriptor.version > current.version) latest.set(descriptor.type, descriptor)
  }
  return latest
}

// ----------------------------------------------------------- zod → field table

/**
 * zod v3 schemas are introspected through `_def`: `typeName` identifies the
 * node, wrappers (`ZodOptional`, `ZodDefault`, `ZodEffects`, `ZodLazy`) hold
 * their target in `innerType`/`schema`/`getter`.
 */
interface ZodNode {
  _def: { typeName: string; [key: string]: unknown }
  description?: string
}

const MAX_DEPTH = 4

function isNode(value: unknown): value is ZodNode {
  return (
    typeof value === 'object' &&
    value !== null &&
    '_def' in value &&
    typeof (value as ZodNode)._def?.typeName === 'string'
  )
}

/**
 * Strip `optional`/`default`/`refine`/`lazy` wrappers, remembering optionality.
 * Every unwrapped `ZodLazy` node is appended to `lazies` so callers can detect
 * a schema that refers back to itself.
 */
function peel(node: ZodNode, lazies?: ZodNode[]): { node: ZodNode; optional: boolean } {
  let current = node
  let optional = false
  for (let i = 0; i < 16; i += 1) {
    const def = current._def
    if (def.typeName === 'ZodOptional' || def.typeName === 'ZodDefault' || def.typeName === 'ZodCatch') {
      optional = true
      current = def.innerType as ZodNode
      continue
    }
    if (def.typeName === 'ZodEffects') {
      current = def.schema as ZodNode
      continue
    }
    if (def.typeName === 'ZodLazy') {
      lazies?.push(current)
      current = (def.getter as () => ZodNode)()
      continue
    }
    if (def.typeName === 'ZodPipeline') {
      current = (def.out ?? def.in) as ZodNode
      continue
    }
    break
  }
  return { node: current, optional }
}

function describeType(node: ZodNode, depth = 0): string {
  if (depth > MAX_DEPTH) return 'unknown'
  const def = node._def
  switch (def.typeName) {
    case 'ZodString':
      return 'string'
    case 'ZodNumber':
      return 'number'
    case 'ZodBoolean':
      return 'boolean'
    case 'ZodDate':
      return 'date'
    case 'ZodNull':
      return 'null'
    case 'ZodObject':
    case 'ZodRecord':
      return 'object'
    case 'ZodLiteral':
      return JSON.stringify(def.value)
    case 'ZodEnum':
      return (def.values as string[]).map((value) => JSON.stringify(value)).join(' | ')
    case 'ZodNativeEnum':
      return Object.values(def.values as Record<string, string>)
        .map((value) => JSON.stringify(value))
        .join(' | ')
    case 'ZodUnion':
    case 'ZodDiscriminatedUnion': {
      // Variants that render identically (a union of object shapes) collapse to
      // one alternative; the field's `.describe()` carries the distinction.
      const options = [...(def.options as Iterable<ZodNode>)]
      const rendered = options.map((option) => describeType(peel(option).node, depth + 1))
      return [...new Set(rendered)].join(' | ')
    }
    case 'ZodArray':
      return `array of ${describeType(peel(def.type as ZodNode).node, depth + 1)}`
    case 'ZodTuple':
      return `tuple of ${(def.items as ZodNode[])
        .map((item) => describeType(peel(item).node, depth + 1))
        .join(', ')}`
    case 'ZodNullable':
      return `${describeType(peel(def.innerType as ZodNode).node, depth + 1)} | null`
    default:
      return 'unknown'
  }
}

/** The object schema whose fields become `<field>.<sub>` rows, if any. */
function objectTarget(node: ZodNode, lazies: ZodNode[], depth = 0): ZodNode | null {
  if (depth > MAX_DEPTH) return null
  const def = node._def
  if (def.typeName === 'ZodObject') return node
  if (def.typeName === 'ZodArray') {
    return objectTarget(peel(def.type as ZodNode, lazies).node, lazies, depth + 1)
  }
  if (def.typeName === 'ZodNullable') {
    return objectTarget(peel(def.innerType as ZodNode, lazies).node, lazies, depth + 1)
  }
  return null
}

interface FieldRow {
  field: string
  type: string
  required: boolean
  meaning: string
}

/**
 * `seen` holds every node already expanded on this path — resolved objects and
 * the `ZodLazy` nodes that produced them. A `z.lazy` getter may mint a fresh
 * object on every call, so the lazy node itself is the only stable identity a
 * recursive schema (checklist `items` → `children`) can be recognised by.
 */
function collectFields(
  object: ZodNode,
  prefix: string,
  seen: readonly unknown[],
  depth = 0,
): FieldRow[] {
  if (depth > MAX_DEPTH) return []
  const shape = (object._def.shape as () => Record<string, unknown>)()
  const rows: FieldRow[] = []
  for (const [name, raw] of Object.entries(shape)) {
    if (!isNode(raw)) continue
    const lazies: ZodNode[] = []
    const { node, optional } = peel(raw, lazies)
    rows.push({
      field: `${prefix}${name}`,
      type: describeType(node),
      required: !optional,
      meaning: (raw.description ?? node.description ?? '').replace(/\s+/g, ' ').trim(),
    })
    const target = objectTarget(node, lazies)
    if (!target) continue
    const markers = [...lazies, target]
    if (markers.some((marker) => seen.includes(marker))) continue
    rows.push(...collectFields(target, `${prefix}${name}.`, [...seen, ...markers], depth + 1))
  }
  return rows
}

// ------------------------------------------------------------ skill section

function cell(text: string): string {
  return text.replace(/\|/g, '\\|')
}

function renderSkillSection(loaded: Loaded[]): string {
  const latest = [...latestByType(loaded).values()]
  const lines: string[] = []
  lines.push(`<!-- ${BANNER.replace('// ', '')} -->`)
  lines.push('')
  lines.push('| type | version | description | use when |')
  lines.push('| --- | --- | --- | --- |')
  for (const descriptor of latest) {
    lines.push(
      `| \`${descriptor.type}\` | ${descriptor.version} | ${cell(descriptor.description)} | ${cell(descriptor.useWhen)} |`,
    )
  }
  for (const descriptor of latest) {
    lines.push('')
    lines.push(`### ${descriptor.type}@${descriptor.version}`)
    lines.push('')
    lines.push('| field | type | required | meaning |')
    lines.push('| --- | --- | --- | --- |')
    const root = descriptor.schema as unknown as ZodNode
    for (const row of collectFields(root, '', [root])) {
      lines.push(
        `| \`${row.field}\` | ${cell(row.type)} | ${row.required ? 'yes' : 'no'} | ${cell(row.meaning)} |`,
      )
    }
    lines.push('')
    lines.push('````markdown')
    lines.push(descriptor.example.replace(/\n+$/, ''))
    lines.push('````')
  }
  lines.push('')
  return `${lines.join('\n')}\n`
}

function renderSkill(current: string, loaded: Loaded[]): string {
  const start = current.indexOf(SKILL_START)
  const end = current.indexOf(SKILL_END)
  if (start === -1 || end === -1 || end < start) {
    throw new Error(
      `${OUTPUTS.skill.pathname} is missing the ${SKILL_START} / ${SKILL_END} markers`,
    )
  }
  const head = current.slice(0, start + SKILL_START.length)
  const tail = current.slice(end)
  return `${head}\n${renderSkillSection(loaded)}${tail}`
}

// ------------------------------------------------------------------- driver

async function build(loaded: Loaded[]): Promise<{ url: URL; content: string }[]> {
  const skill = renderSkill(await readFile(OUTPUTS.skill, 'utf8'), loaded)
  const artifacts = [
    { url: OUTPUTS.registry, content: renderRegistry(loaded) },
    { url: OUTPUTS.renderers, content: renderRenderers(loaded) },
    { url: OUTPUTS.names, content: renderNames(loaded) },
    { url: OUTPUTS.skill, content: skill },
  ]
  if (existsSync(OUTPUTS.claudeSkill)) {
    artifacts.push({ url: OUTPUTS.claudeSkill, content: skill })
  }
  return artifacts
}

const rootPath = fileURLToPath(repoRoot)

const mode = process.argv[2]
if (mode !== '--write' && mode !== '--check') {
  console.error('Usage: component-docs.ts --write|--check')
  process.exit(2)
}

const loaded = await loadDescriptors()
const artifacts = await build(loaded)

if (mode === '--write') {
  for (const artifact of artifacts) await writeFile(artifact.url, artifact.content)
  console.log(
    `Generated component docs for ${loaded.map((e) => `${e.descriptor.type}@${e.descriptor.version}`).join(', ')}.`,
  )
} else {
  const stale: string[] = []
  for (const artifact of artifacts) {
    let current: string
    try {
      current = await readFile(artifact.url, 'utf8')
    } catch {
      current = ''
    }
    if (current !== artifact.content) stale.push(fileURLToPath(artifact.url).slice(rootPath.length))
  }
  if (stale.length > 0) {
    console.error(
      `Generated component docs have drifted. Run pnpm components:docs:generate.\n${stale
        .map((path) => `  stale: ${path}`)
        .join('\n')}`,
    )
    process.exit(1)
  }
  console.log('Generated component docs are up to date.')
}


