// Generated by scripts/component-docs.ts — do not edit.
export const COMPONENT_TYPES = ['checklist', 'datatable', 'embed', 'figure'] as const
export const COMPONENT_LATEST_VERSION: Record<string, number> = {
  checklist: 1,
  datatable: 1,
  embed: 1,
  figure: 1,
}
