import type { WikiKindRegistry } from './kind-registry.js'

export function renderWikiKindGuidance(registry: WikiKindRegistry): string {
  const lines = [
    '# Wiki kind reference (generated)',
    '',
    'Generated from `packages/core/src/wiki/kinds.json`. Do not edit this file.',
    'Run `pnpm wiki:kinds:generate` after editing the registry.',
    'Read [shared page rules](page-rules.md) for identity, evidence and migration safety.',
    'Use `memon wiki kinds ls` or `memon wiki kinds show <kind>` to inspect the installed runtime.',
    '',
  ]
  for (const kind of [...registry.kinds].sort((left, right) => left.order - right.order)) {
    lines.push(
      `## ${kind.id}`,
      '',
      kind.en.purpose,
      '',
      `Suitable uses: ${kind.en.uses.join('; ')}`,
      '',
      `Examples (advisory): ${kind.en.examples.join('; ')}`,
      '',
      `Distinctions: ${kind.en.distinctions}`,
      '',
      kind.en.authoring,
      '',
      `- Status vocabulary: ${kind.policy.statuses.join(' / ') || 'none'}.`,
      `- Creation default: ${kind.policy.statuses[0] ?? 'no status'}.`,
      `- Date required: ${kind.policy.dateRequired ? 'yes (YYYY-MM-DD)' : 'no'}.`,
      `- Non-empty sources required: ${kind.policy.sourcesRequired ? 'yes' : 'no'}.`,
      `- Recommended H2s (warning only; also used by create): ${kind.policy.recommendedHeadings.join(', ') || 'none; free-form'}.`,
      '- Required H2s: none.',
      `- Body evidence warning: ${kind.policy.bodyEvidenceWarning ? 'yes' : 'no'}.`,
      `- Human-review warning at status: ${kind.policy.reviewWarningStatus ?? 'none'}.`,
      `- Related kinds: ${kind.relatedKinds.join(', ') || 'none'}.`,
      '',
    )
  }
  lines.push(
    '## Reserved directories',
    '',
    registry.reservedIds.map((id) => `\`${id}\``).join(', '),
    '',
    'These are not canonical page kinds. Unknown kinds remain readable but produce diagnostics.',
    'Use explicit move/migration commands; registry edits never rewrite or review pages.',
    '',
  )
  return lines.join('\n')
}
